name = "Shion-Squishy House Pack Thingy"
author = "Lucy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cbe1378287ca728a2d8770c7d5678fac19041d6145683ce81858e2d7dbe7ad5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
