name = "Shion-Squishy House Pack Thingy"
author = "Lucy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2af9408a5f871860f61fb3db37cd63fc72204cfe178bcdbe39e741838c21a13f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
