name = "Shion-Squishy House Pack Thingy"
author = "Lucy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a072cae3b3af9a95ebb872c2649a886bab8bdf265e7ca310edc8497e1255563"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
